apiVersion: v1
kind: Pod
metadata:
  name: cleanup-job
  namespace: default  # Change this if needed
spec:
  serviceAccountName: dev-sa  # Ensure this matches your Kubernetes RBAC service account
  restartPolicy: Never  # Run the job once and exit
  containers:
    - name: cleanup-job
      image: python:3.10  # Use official Python image
      command: ["python3", "/app/cleanup.py"]
      volumeMounts:
        - name: script-volume
          mountPath: /app
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace  # Get the namespace dynamically
  volumes:
    - name: script-volume
      configMap:
        name: cleanup-script  # This will hold the Python script
