apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-genai-resources
spec:
  schedule: "0 * * * *"  # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: dev-sa  # Ensure SA has permissions
          restartPolicy: Never
          containers:
            - name: cleanup-genai-resources
              image: bitnami/kubectl:latest  # Lightweight image with kubectl pre-installed
              command:
                - /bin/sh
                - -c
                - |
                  kubectl get all -o=jsonpath='{range .items[?(@.metadata.annotations.deployer)]}{.kind}/{.metadata.name} {.metadata.creationTimestamp}{"\n"}{end}' | \
                  while read resource timestamp; do
                    create_time=$(date -d "$timestamp" +%s)
                    now=$(date +%s)
                    age=$(( (now - create_time) / 3600 ))  # Convert to hours
                    if [ "$age" -ge 36 ]; then
                      echo "Deleting $resource (created $age hours ago)"
                      kubectl delete "$resource"
                    fi
                  done
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace  # Runs in the current namespace only
              securityContext:
                allowPrivilegeEscalation: false
                runAsUser: 1000
                runAsGroup: 1000
                readOnlyRootFilesystem: true
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir: {}
